[
  ["white",null,"white","white","white","black",null,"black","white"],
  [null,"white","white","white","black","black",null,"black","white"],
  ["white","white","black","black","black","black","black","black","white"],
  ["white","black","black","black","white","black","white","white","white"],
  ["white","black","black","white","white","black","white",null,null],
  ["black","black","black","black","white","white",null,"white",null],
  ["black",null,"black","black","white","white",null,"white",null],
  ["black","black","white","white","white",null,null,"white",null],
  ["white","white","white","white",null,null,null,"white",null]
];
